version: 2

jobs:
    test:
      docker:
        - image: continuumio/anaconda3:5.0.1
      steps:
        - checkout
        - run:
            command: |
              conda create -n acheron python=3.7.9 anaconda
              source activate acheron
              conda env update --file data/envi.yaml
              pip install -e .
              pytest tests

workflows:
  version: 2
  all:
    jobs:
      - test
