version: 2

jobs:
    test:
      docker:
        - image: continuumio/anaconda3:5.0.1
      steps:
        - checkout
        - run:
            no_output_timeout: 30m
            command: |
              conda env create -f data/envi.yaml
              source activate acheron
              pip install -e .
              pytest tests

workflows:
  version: 2
  all:
    jobs:
      - test
